image:
  file: .gitpod.Dockerfile
tasks:
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
    name: Use Pulumi
    command: pulumi version
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
    name: Install Python Requirements
    init: pip install -r requirements.txt
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
    name: Use Azure 
    init: brew install azure-cli
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no"
    name: Use GH 
    init: brew install gh
  - before: "echo 'export PIP_USER=no' >> ~/.bashrc && export PIP_USER=no" 
    name: Run Doppler 
    init: brew install gnupg & brew install dopplerhq/cli/doppler


github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: false
