name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, development, development-pulumi ]
  pull_request:
    branches: [ main, development, development-pulumi ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Preview:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: actions/checkout@v3
    - name: Install Python Requirements
      run: |
        pip install -r requirements.txt
    - name: Set Pulumi 
      run: |
        pulumi stack select ${{ secrets.PULUMI_STACK_NAME }} 
        pulumi config set azure-native:clientId ${{ secrets.AZUZRE_CLIENT_ID }} 
        pulumi config set azure-native:clientSecret ${{ secrets.AZURE_CLIENT_SECRET }} --secret 
        pulumi config set azure-native:tenantId ${{ secrets.TENANT_ID }} 
        pulumi config set azure-native:subscriptionId ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        pulumi preview
      env: 
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          

          
