name: Django CI 

on:
  pull_request:
    branches: 
      - development 
      - main
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
       with:
         python-version: ${{ matrix.python-version }}
   - name: Install poetry
      run: pipx install poetry
   - uses: actions/setup-python@v3
      with:
         python-version: '3.9'
         cache: 'poetry'
    - run: poetry install
    - name: Run Linting
       run: |
         poetry add black 
         poetry run black .
    - name: Run Tests
       run: |
         poetry run python manage.py test
        
        
