name: Docker Image CI

on:
  push:
    branches: 
     - development
  pull_request:
    branches: 
     - development

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USERNAME }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_TOKEN }}
        # Log out from the Docker registry at the end of a job
        logout: true
    - name: Build & Publish the Docker Image
      run: docker build . --file Dockerfile --tag supacoda:latest && docker push harleydev/supacoda
